# Generated by Django 3.0.5 on 2020-06-02 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagepath', models.ImageField(upload_to='images/')),
                ('Emailt', models.CharField(max_length=200)),
                ('Subject', models.CharField(max_length=50)),
                ('Branch', models.CharField(max_length=20)),
                ('Sem', models.CharField(max_length=20)),
                ('Div', models.CharField(max_length=20)),
                ('Date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('Emailt', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Emails', models.EmailField(max_length=200)),
                ('Emailt', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Roll', models.CharField(max_length=200)),
                ('personID', models.CharField(max_length=200)),
                ('Branch', models.CharField(max_length=20)),
                ('Sem', models.CharField(max_length=20)),
                ('Div', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
    ]
